### PR TITLE
Improved the capabilities of add_gradient_fill

### PR DESCRIPTION
**Pull request by cedrichol**
add_gradient_fill() now supports:
- log plots (solves issue #17)
- having a tuple(minimum, maximum) alpha instead of a single float (which is still supported)
- Starting the gradient at:
    - the bottom of the plot (like the underglow, solves issue #16)
    - the minimum of the line (previous behaviour)
    - the top of the plot
    - the max of the line
    - zero (the visual effect is really nice depending on the signification of the data...)
- choosing the number of sampling points

Other improvements :
- internally imshow() is called with [interpolation='bilinear'], which helps reduce the necessary sampling points for linear plots
- xlims and ylims are now saved and restored, as add_underglow() does, for the same reasons

test_plotting_gradient() shows the capabilities of this implementation:
test_gradient_fill

### CODE REVIEW

**Comment by diceroll123** [comment]
My hopes were risen and dashed when I thought this fixed #15! 😭 

That aside, looks amazing. Great work!

**Comment by cedrichol** [comment]
Thanks !

As for #15, I might take a look at it, it might be doable

**Comment by dhaitz** [comment]
wow, this looks really awesome, especially with the doctoring, tests and detailed PR! Thanks for your contribution. I've made some minor edits (mostly naming), should be fine now!

**Comment by diceroll123** [comment]
I've closed #15 and #16 as completed now.

#17 can be closed, me thinks.

**Comment by cedrichol** [comment]
Happy you like it, thanks for this cool project btw

**Pull request merged**
